### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Toxic2Venom** [techbelly/di-usb-library#3]
What version of python do we use? This isn't specified. Please help.

**Comment by techbelly** [comment]
I'm sorry, I can't remember, but it looks like python 3. I did need to install hidapi. If you're having trouble post me a specific error that you're seeing and maybe I can help.

**Comment by awesomecoder3000** [comment]
This is my error
Traceback (most recent call last):
  File "PATH-TO-FILE/di-usb-library-master/color.py", line 2, in <module>
    from infinity import InfinityBase
  File "PATH-TO-FILE/di-usb-library-master/infinity.py", line 9
    self.finish = False
    ^
IndentationError: unexpected indent

**Comment by awesomecoder3000** [comment]
(The up arrow is on the E in falsE)

**Comment by awesomecoder3000** [comment]
Fixed! But know I have a new error, HIDAPI isn’t found, I’ve installed at least different kinds

**Comment by xtoadette** [comment]
> This is my error
> Traceback (most recent call last):
> File "PATH-TO-FILE/di-usb-library-master/color.py", line 2, in
> from infinity import InfinityBase
> File "PATH-TO-FILE/di-usb-library-master/infinity.py", line 9
> self.finish = False
> ^
> TabError: inconsistent use of tabs and spaces in indentation

how did you fix this problem? i'm having the same issue.
